### ISSUE TITLE
Example in Readme does not compile!

### ISSUE THREAD

**Issue by nidhind** [kenshaw/escpos#18]
The example provided in Readme fails with following error on `go build main.go`
```
# command-line-arguments
./main.go:18:17: cannot use w (type *bufio.Writer) as type io.ReadWriter in argument to escpos.New:
        *bufio.Writer does not implement io.ReadWriter (missing Read method)
```

`go version go1.15 linux/amd64`

**Comment by philipgreat** [comment]
Please fix like this:

   defer f.Close()
    r := bufio.NewReader(f)
    w := bufio.NewWriter(f)
    rw := bufio.NewReadWriter(r,w)
    p := escpos.New(rw)

**Comment by mcluseau** [comment]
Hi, thanks for the fix, I've updated the README.

**Comment by jbpratt** [comment]
Hi @mcluseau ,

The problem still persists

```
tmp >go mod init tmp
go: creating new go.mod: module tmp
tmp >go build main.go
go: finding module for package github.com/knq/escpos
go: downloading github.com/knq/escpos v0.0.0-20201012084129-81d0344e35fa
go: found github.com/knq/escpos in github.com/knq/escpos v0.0.0-20201012084129-81d0344e35fa
# command-line-arguments
./main.go:18:17: cannot use w (type *bufio.Writer) as type io.ReadWriter in argument to escpos.New:
	*bufio.Writer does not implement io.ReadWriter (missing Read method)
``` 

The actual problem is that https://github.com/kenshaw/escpos/blob/81d0344e35fafe5bda5dc2b6adf43d8abcff36c7/escpos.go#L83 is expecting an `io.ReadWriter` where as the example creates a `bufio.Writer` https://golang.org/pkg/bufio/#NewWriter

As per @philipgreat 's comment, removing the `bufio.NewWriter(f)` and the `w.Flush()` at the end will fix this issue.
